<a href="https://colab.research.google.com/github/moreymat/scpo-data-science-bootcamp/blob/main/notebooks/1_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python basics

Welcome to the "Data science bootcamp" in Python.

In this notebook, the first in a series, you will see the basics of the Python programming language, a fundamental tool nowadays for data science, artificial intelligence and machine learning.

This notebook is mostly (and heavily) derived from the notebook [Python basics](https://colab.research.google.com/github/data-psl/lectures2020/blob/master/notebooks/01_python_basics.ipynb#scrollTo=clWaFCzBMfkv), authored by Mathieu Blondel for the [preparatory week of the transverse program for data sciences at Université PSL (Paris Sciences & Lettres)](https://data-psl.github.io/preparatory-week/).

## Preamble : Colaboratory and notebooks

We are working on a platform, [Google Colaboratory](https://colab.research.google.com), that enables users to edit and run [Jupyter notebooks](https://en.wikipedia.org/wiki/Project_Jupyter#Jupyter_Notebook) in the cloud for free, without any installation, and with access to GPUs.

For a very short history and description of Colaboratory, see [on wikipedia](https://en.wikipedia.org/wiki/Project_Jupyter#Google_Colaboratory).

### Note on how to change the language on Google Colaboratory

Google Colaboratory uses the default language settings from your web browser.
If the menus are displayed in a different language, you can switch to English by going to (the equivalent of) the "Help" menu, then clicking on (the translation of) the item "Display in English".

<center>
<img src="https://github.com/moreymat/scpo-data-science-bootcamp/raw/main/notebooks/img/colab-lang.png" width=400>
</center>

Having the interface in English will ensure you can easily follow the instructions and advice in these notebooks.

### Using a notebook

All our work will happen inside a *notebook*, an interactive document where you can write a mix of :

* text formatted in [Markdown](https://guides.github.com/features/mastering-markdown/) that is rendered, and
* code in [Python](https://www.python.org/) that can be executed.

More precisely, a notebook consists in a sequence of *cells*, where each cell contains either (Markdown) text or (Python) code.

Notebooks are not limited to text and code, they can render math equations, images, plain HTML content and even interactive widgets !
But in this series of notebooks, we will mostly write text and code.

You can double click on any text cell to edit it.

By default, Colab shows you the Markdown text on the left and a preview of its rendering on the right that is updated (almost) in real time as you type.

When you are done, just press "Shift+Enter" and the cell will be rendered.


### Markdown basics

Markdown relies on characters, in particular the star `*` (or multiply).

*Text between stars is in italic*, **text between pairs of stars is in bold**.

A sequence of lines that start with a star is rendered as a list with bullets :

* first item
  - subitem for the first item
* second item
* third item

Lines that start with one or more hash `#` are headings :

* 1 hash `#` for level-1 headings (document title),
* 2 hashes `##` for level-2 headings (section title),
* 3 hashes `###` for level-3 headings (subsection title).

Links are defined by two elements : the text of the link between square brackets `[` and `]`, and the target of the link between parentheses.
As an example, here is a link to the [Sciences-Po website](https://www.sciencespo.fr/en/home).

If you want to add a text (or code) cell after the cell you are currently editing, you can either :
* click on the menu item "Insert" > "Text cell" (or "Code cell"), or
* hover your mouse 1-2 mm below the bottom of the cell and click on one of the two buttons "+ Code" and "+ Text" that appear.

<center>
<img src="https://github.com/moreymat/scpo-data-science-bootcamp/raw/main/notebooks/img/colab-add-cell.png" width=400>
</center>

If you forget the Markdown syntax for the most commonly used elements, the menu bar that appears at the top of a text cell (when you edit it) displays a familiar interface with clickable buttons.

<center>
<img src="https://github.com/moreymat/scpo-data-science-bootcamp/raw/main/notebooks/img/colab-markdown-buttons.png" width=400>
</center>

A smaller bar appears on the upper right corner of the cell, with "up" and "down" arrows to move the cell up or down, a button to delete the cell, etc.

<center>
<img src="https://github.com/moreymat/scpo-data-science-bootcamp/raw/main/notebooks/img/colab-cell-upper-right.png" width=200>
</center>

There are many resources online to learn more about the Markdown syntax, eg. the [Markdown page on Wikipedia](https://en.wikipedia.org/wiki/Markdown) or this [short tutorial by GitHub](https://guides.github.com/features/mastering-markdown/).

**Exercise.** Add a text cell below this one, and write a very short text with the following constraints :

* the text consists of 3 sections,
* each section consists of 2 subsections,
* one subsection must contain a bullet list,
* another subsection must contain a numbered list,
* another subsection must contain a two-level bullet list, where two items have at least 3 sub-items each.

Any text will do, so feel free to write nonsensical text if you feel uninspired, or reuse some common placeholder text such as [Lorem ipsum](https://en.wikipedia.org/wiki/Lorem_ipsum).

### Python in the notebook

Notebooks can contain code cells, that you can edit, like you do for text cells, but writing Python syntax instead of Markdown, and execute.

A code cell contains one or more Python instructions.

For example, here is a code cell that computes the number of seconds in a day (`24 * 60 * 60`), stores the result in a variable (`seconds_in_a_day`) and prints its value:

In [2]:
seconds_in_a_day = 24 * 60 * 60
print(seconds_in_a_day)

86400


Click on the "play" button on the left of the cell to execute it.
You should be able to see the result.

Alternatively, you can also execute the cell by pressing "Ctrl+Enter" if you are on Windows or Linux, "Command+Enter" if you are on a Mac.

In notebooks, another way to display the value of a variable is just to type its name.

In [3]:
seconds_in_a_day

86400

Variables that you defined in one cell can later be used in other cells, be it to display their value as we just did, or to use their value in a computation:

In [4]:
seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

604800

Note that the order of execution is important.
For instance, had we not run the cell that computes and stores `seconds_in_a_day` beforehand, executing the above cell would have raised an error, as it depends on this variable.

To make sure that you run all the cells in the correct order, the easiest option is to click on "Runtime" in the top-level menu, then on the "Run all" item.

If you want to display the value of more than one variable, you need to use `print`.

In [5]:
print(seconds_in_a_day)
print(seconds_in_a_week)

86400
604800


You cannot achieve the same effect by just typing the two variable names on separate lines, because the notebook only displays the value of the last instruction:

In [6]:
seconds_in_a_day
seconds_in_a_week

604800

**Exercise.** Add a Code cell below this cell. In the new cell, compute the number of seconds in a [common year](https://en.wikipedia.org/wiki/Common_year) by reusing the variable `seconds_in_a_day` and print it. Run the new cell.

## Python

Let us start with basic notions of the Python programming language.

### Numbers and arithmetic operations

Python enables to manipulate numeric values of various types :
* [integers](https://en.wikipedia.org/wiki/Integer_(computer_science)) (`int`),
* [booleans](https://en.wikipedia.org/wiki/Boolean_data_type) (`bool`),
* [real numbers](https://en.wikipedia.org/wiki/Floating-point_arithmetic) (`float`),
* [complex numbers](https://en.wikipedia.org/wiki/Complex_data_type) (`complex`),



On these numeric values, Python supports the usual arithmetic operators :

* `+` (addition),
* `*` (multiplication),
* `/` (division),
* `**` (power),
* `//` (integer division ; see [Wikipedia](https://en.wikipedia.org/wiki/Division_(mathematics)#Of_integers), item numbered 5).

In general, you do not need to explicitly state the type of a numeric value because Python guesses from the writing.

In [ ]:
# (a line starting with a hash '#' in Python is a comment, it is not interpreted)
# let us declare an integer
x = 1
# and display its value, just by calling its name
x

1

In [ ]:
# let us declare a float
y = 3.2
# and display its value
y

3.2

If you sum an integer and a real number, Python will automatically convert the integer to a float before doing the computation.

In [ ]:
z = x + y
z

4.2

**Exercise.** Add code cells and try out each of the remaining arithmetic operations, with various values.

Ill-defined operations will raise an error, such as a division by zero.

In [ ]:
wrong_comp = 14 / 0

ZeroDivisionError: ignored

The "stop signal" on the left of the cell signals that the execution of this Python block has failed.

The error message provides you with (hopefully) useful information to know what went wrong.
If you do not know what the error means, or how to fix it, click on the "Search stack overflow" button and read from the suggested webpages.

### Functions

To improve code readability, it is common to separate the code into different blocks, responsible for performing precise actions: **functions**.

A function takes some **inputs** (or *arguments*) and processes them to return some **outputs** (or *results*).



Visually, a function definition is a block of lines that:
- begins with a line starting with the keyword `def`,
- includes all subsequent lines **indented** at least one more level than `def` (ie. vertically aligned at least one `<TAB>`, or two regular whitespaces, further to the right than `def`),
- ends as soon as we encounter a line at the same level of indentation as `def`.


*Nota Bene*: The Python language relies on indentation (vertical alignment) to define the precise scope of not only functions, but also various constructs that you will discover shortly.

For instance, let us define a function `square` that, for an input `x`, computes and returns as output `x ** 2`.

In [ ]:
def square(x):
  return x ** 2

The first line relies on three concepts :

* The reserved keyword `def` signals a function definition ;
* This function is named `square` ;
* It expects one or more arguments listed between parentheses, here a unique argument that we name `x`, we will use this name `x` to refer to the argument value in the body of the function.

This first line ends with a colon `:` that separates the signature of the function (function name and list of arguments) from the body of the function (the sequence of instructions that describe the computation that this function does).

Syntactically, the body of a function is defined as the sequence of lines that are **indented** at least one level (one `<TAB>`, or two regular whitespaces) further to the right.
Here, the body of the function is a single line `return x ** 2`, but most functions perform more complex operations hence are longer than that.

The second line uses two concepts :

* The reserved keyword `return` signals that what comes next on this line will be the value output by the function ;
* The returned (output) value is defined as the result of the arithmetic operation `x ** 2`.

Any line in the body after `return` will not be executed, because `return` triggers an output and the exit of the function.

We can apply the `square` function to a number :

In [ ]:
square(4)

16

Functions can have more than one argument.

In [ ]:
def multiply(a, b):
  return a * b

multiply(3, 5)

15

In the cell above :

* the function `multiply` is defined that expects two arguments named `a` and `b`, and returns the result of their multiplication ;
* after the function is defined, we apply it to the pair of values `3` and `5`.

But how does the Python interpreter know that the function body ends after `return a * b`, and does not include `multiply(3, 5)` ?

If you edit the cell, remove the empty line and re-run the cell, you will see that the behavior is the same as before.
You can try it and see for yourself.

This unchanged behavior with and without the empty line means that the empty line does not mark the end of a function body.

Another possibility could be that `multiply(3, 5)` is not indented at the same level as the `return a * b` line, but rather is indented at the same level as the `def` keyword that starts the function definition.

Indeed, the uninterrupted sequence of instructions whose start is indented further to the right than the `def` line, makes up the function body.

Starting a line at the same indentation level as the `def` line marks the end of the function body.


Functions can be composed : A function can be applied to the output of another function.

In [ ]:
# Functions can be composed.
square(multiply(3, 2))

36

To improve code readability, it is sometimes useful to explicitly name the arguments.

In [ ]:
square(multiply(a=3, b=2))

36

Naming the arguments also provides flexibility, because you can use these names when you call the function and avoid having to remember the order in which the arguments were stated in the function definition.

**Exercise.** Write a `divide(a, b)` function. Compare the results returned by `divide(15, 3)`, `divide(3, 15)`, `divide(a=15, b=3)`, `divide(b=3, a=15)`.

### Lists

A fundamental capacity in programming is to operate not only on simple values, but also on collections of values (or more complex objects).

Python provides several data structures to hold such collections, the simplest being the list.

Lists are a container type for ordered sequences of elements.

Lists can be initialized empty

In [ ]:
my_list = []

or with some initial elements

In [ ]:
my_list = [1, 2, 3]

Lists have a dynamic size : elements can be added, *appended*, to them (at the end).

In [ ]:
my_list.append(4)
my_list

[1, 2, 3, 4]

We just used a new syntax here, which is the *dot notation* : on the variable `my_list`, we applied an operation, [append](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists), with the value `4` as its argument.

`append` is a *method* of list objects, ie. a function that is attached to every list.

Here, calling `.append(4)` on `my_list` had the effect of modifying `my_list` by adding a new element, 4, at its end.

We can access individual elements of a list with their position or *index*.
Note that in Python, **indexing starts from 0**.

In [ ]:
# access element at index 0 (hence the 1st value in the list)
my_list[0]

1

In [ ]:
# access element at index 3 (hence the 4th value in the list)
my_list[3]

4

We can access "slices" of a list using `my_list[i:j]` where `i` is the start of the slice (again, indexing starts from 0) and `j` the end of the slice.

In the slice notation :

* the start index is *included* ;
* the end index is *excluded*.

For instance, to get elements from position 1 (included) to 3 (excluded), ie. elements at positions 1 and 2 :

In [ ]:
my_list[1:3]

[2, 3]

Omitting the second index means that the slice shoud run until the end of the list.

In [ ]:
my_list[1:]

[2, 3, 4]

We can check if an element is in the list using (the binary operator) `in`.

In [ ]:
5 in my_list

False

The length of a list can be obtained using the `len` function.

In [ ]:
len(my_list)

4

**Exercise.** Add a Code cell and define a list of strings 'a', 'b', 'c', 'd', 'e'. Select the slice from position 2 (included) to position 5 (excluded). Then select the slice from position 0 (included) to 3 (excluded).

### Strings

Computers can manipulate not only numeric values, but also text values.

Text values are stored in *strings*.
In Python, strings are enclosed in single quotes `'` or double quotes `"`.

In [ ]:
string1 = "some text"
string2 = 'some other text'

Strings behave similarly to lists.
As such we can access individual elements in exactly the same way, by specifiying their index.

In [ ]:
string1[3]

'e'

and similarly, we can take a slice of a string

In [ ]:
string2[5:]

'other text'

String concatenation is performed using the `+` operator.

In [ ]:
string1 + " " + string2

'some text some other text'

### Conditionals

As their name indicates, conditionals are a way to execute code depending on whether a condition is `True` or `False`.

As in other languages, Python supports `if` and `else` but `else if` is contracted into `elif`, as the example below demonstrates.

We will use the `print()` function to print a message below the code cell at execution.

In [ ]:
my_variable = 5
if my_variable < 0:
  print("negative")
elif my_variable == 0:
  print("null")
else: # my_variable > 0
  print("positive")

positive


Here `<` and `>` are the strict "less than" and "greater than" operators, while `==` is the equality operator (not to be confused with `=`, the variable assignment operator).

The operators `<=` and `>=` can be used for "less than or equal" and "greater than or equal" comparisons.

**Nota Bene**: The `print` function used here merely displays the given text in the notebook, below the code cell.
This is very different from the `return` statement used to output a value in a function.
The value returned by a function can be stored in a variable, passed to another function and so on, whereas the only use of printed text is that you can read it on the screen.


**Reminder**: Contrary to other languages, blocks of code are delimited using indentation.
Here, we use 2-space indentation but many programmers also use 4-space indentation.
Any one is fine as long as you are consistent throughout your code.

### Loops

Loops are a way to execute a block of code multiple times.
There are two main types of loops: `for` loops and `while` loops.

- `for` loops are simple to use. You will need to use `for` loops in these notebooks, and in your future projects, therefore it is important for you to understand this construct.

- `while` loops are more flexible and enable to perform more complex processing, more also more error-prone. You might encounter `while` loops in the future, perhaps even need to write `while` loops yourself, so it is important that you know they exist. No need to panic if you do not get them immediately though !

#### For loops
A `for` loop is executed once for each element in a sequence.

A `for` loop is very convenient if your goal is simply to **iterate over each element in a list**, one after the other, and do something with it.

For instance, if we want to print each element in `my_list`, from the first to the last :

In [ ]:
for element in my_list:
  print(element)

1
2
3
4


Because a `for` loop can be used to iterate over any list, you can also use it to retrieve elements by their **indices**.
For instance, if you want to print the elements at indices 0, 1 and 3 in `my_list`, you can write :

In [ ]:
for i in [0, 1, 3]:
  print(my_list[i])

1
2
4


**Convention.** It helps to use variable names that clearly convey what is being manipulated. In the above cells, I used two variable names in my `for` loops:

* `element` to iterate over the *elements* of a list,
* `i` to iterate over the *indices* (positions) in a list.

These naming conventions aim at conveying the nature of iteration variable and its intended use.

You can use different names in your own loops, though, as long as these names help you (or eventual readers of your code) understand the nature and possible uses of the content of these variables.

What if we want to iterate over a consecutive range of positions, let us say print the first 10 elements of a long list such as this one :

In [ ]:
my_big_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
               'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
               'u', 'v', 'w', 'x', 'y', 'z']

The long, tedious version would be :

In [ ]:
for i in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]:
  print(my_big_list[i])

a
b
c
d
e
f
g
h
i
j


A more concise way would be to generate the sequence of consecutive numbers from 0 (included) to 10 (excluded), corresponding to the first 10 indices (positions) of the elements in the list, with the [range](https://docs.python.org/3.7/tutorial/controlflow.html#the-range-function) function.

In [ ]:
for i in range(0, 10):
  print(my_big_list[i])

a
b
c
d
e
f
g
h
i
j


Read the documentation for `range` in the above link if you want to know more about the various ways `range` can be called.

### Combining notions (optional)

We saw earlier that the `len()` function returns the length of a list, which is an integer :

In [ ]:
len(my_list)

4

An alternative way to iterate over a list, rather than iterating over elements directly, is to iterate over each position (*index*) `i` in the list from 0 (included) to the length of the list (excluded), retrieve the element at position `i` and print it :

In [ ]:
for i in range(len(my_list)):
  print(my_list[i])

1
2
3
4


**Exercise.** Write two equivalent `for` loops whose effect is to print each element in `my_big_list` using :
(a) an iteration over elements,
(b) an iteration over indices.

#### While loops

A `while` loop goes on as long as its condition is True.

The condition of a `while` loop can be any expression that can be evaluated to either `True` or `False`.
You need to make sure that this expression is initially `True` (otherwise the loop will never be executed), but eventually becomes `False` (otherwise the loop will never stop and it will run forever).

We can use a `while` loop to do the same thing we did earlier, that is iterating over each index in a list to retrieve the element at that index and print it.

But we need to do more work ourselves :

* before the `while` operator, we need to declare the `i` variable ourselves and set it to its initial value (0) ;
* at the end of each iteration, we need to increase the value of `i` by 1 so that the next iteration will retrieve the next element.

In [ ]:
i = 0
while i < len(my_list):
  print(my_list[i])
  i += 1 # equivalent to i = i + 1

1
2
3
4


Before the loop, `i` is set to 0.

Then as long as `i` is smaller than the length of the list, we print the element at position `i`, then increase `i` by 1.

At the next iteration, if `i` is still smaller than the length of the list, the same thing happens, otherwise (if `i` is greater than or equal to the length of the list) the body of the loop is not executed.

### Dictionaries

Dictionaries enable to store key - value pairs, or mappings.

For instance, we can map the numbers of the [Departments of France](https://en.wikipedia.org/wiki/Departments_of_France) to their names.

In [ ]:
fr_deps = {
    '13': 'Bouches-du-Rhône',
    '75': 'Paris',
}

fr_deps

{'13': 'Bouches-du-Rhône', '75': 'Paris'}

A dictionary enables you to provide a key, between square brackets, and retrieve the value associated to this key.



In [ ]:
fr_deps['13']

'Bouches-du-Rhône'

If you already have a dictionary, but want to add a new key - value pair, you can use an assignment similar to that for values but with the square brackets notation :

In [ ]:
fr_deps['59'] = 'Nord'

If the key does not exist in the dictionary, the key - value pair is added ; If the key already exists in the dictionary, the associated value is replaced with the new one.

### Exercises

**Exercise 1.** Write a function `relu` that, given a number `x`:
- if `x` is greater than or equal to 0, returns `x`,
- otherwise (ie. if `x` is negative) returns `0`.

> **HINT** Use a conditional.

In [ ]:
relu(-3)  # should be 0

0

In [ ]:
relu(31)  # should be 31

31

This function could be used to compute corporate tax in simplistic software, where one assumes the taxable income of a company to be its net profit, unless the company had losses in which case its taxable income amounts to 0.

As a matter of fact, this function is widely used to model phenomena in various domains.

You might encounter it later in the semester when you use neural networks to uncover biases in AI systems, under the name [Rectifier or Rectified Linear Unit (ReLU) activation function](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)).

Formally, it is defined by the following formula:

$\text{relu}(x) = \left\{
   \begin{array}{rl}
     x, & \text{if }  x \ge 0 \\
     0, & \text{otherwise }.
   \end{array}\right.$


The notation might scare you at first, but it is a mere notation for the function you just wrote.

Congratulations, you wrote one of the basic building blocks of neural networks !

**Exercise 2.** Using a foor loop, write a function that computes the [average](https://en.wikipedia.org/wiki/Average) of a list of values.

In [ ]:
def average(vector):
  # write your function here
  return

my_vector = [12, 11, 9, 5, 7]
# the result should be 8.8
average(my_vector)


**Exercise 3.** Using a for loop and a conditional, write a function that returns the maximum value in a vector.

In [ ]:
def vector_maximum(vector):
  # Write your function here
  return

In [ ]:
# the result should be 8
vector_maximum([1, -2, 8, 4, -1])

**Bonus exercise.** If you still have time, write a function that sorts a list in ascending order (from smaller to bigger) using the [insertion sort](https://en.wikipedia.org/wiki/Insertion_sort) algorithm.

In [ ]:
def insertion_sort(my_list):
  # Write your function here
  return

my_list = [1, -3, 3, 2]
# Should return [-3, 1, 2, 3]
insertion_sort(my_list)

The outer loop goes over all indices from 1 to the length of the list. This is a case where a for loop is more explicit and feels more natural in Python.

In [ ]:
# alternative: more Python-esque version
def insertion_sort_alt(my_list):
  # Write your function here

# Should return [-3, 1, 2, 3]
insertion_sort_alt(my_list)

Insertion sort is a simple sorting algorithm. Other sorting algorithms operate differently, eg. [bubble sort](https://en.wikipedia.org/wiki/Bubble_sort) or [quicksort](https://en.wikipedia.org/wiki/Quicksort). Sorting algorithms arrive at the same result (a sorted list) by following different logics, which will perform differently in the best, average or worst case scenarios.

### Going further

We covered some essential of the Python programming language, but it has many more features.

If or when you have time, you can check out these resources :

* [Ultimate Python study guide](https://github.com/huangsam/ultimate-python)
*   List of Python [tutorials](https://wiki.python.org/moin/BeginnersGuide/Programmers)
* Four-hour [course](https://www.youtube.com/watch?v=rfscVS0vtbw) on Youtube (you can skip the parts on PyCharm, files etc. if you only work on Colaboratory)
* [Automate the Boring Stuff with Python - Practical Programming for Total Beginners]((https://automatetheboringstuff.com/)) by Al Sweigart is Sylvain's (and many others') favorite. It is "written for office workers, students, administrators, and anyone who uses a computer to learn how to code small, practical programs to automate tasks on their computer."
The entire content of the book is available on its website, scroll down to the "Table of contents" and you will see links to each chapter.


## NumPy

Computers are designed so that it is more efficient to apply an operation on an array of numbers at once, in bulk, rather than on each number in turn.
Pure Python code, using only the Python standard library, do not enable you to do that.

### Gaining functionalities with libraries

This can be remedied by using an additional [software library](https://en.wikipedia.org/wiki/Library_(computing)), which is, roughly speaking, a collection of code that provides functionalities to perform operations on a given task or domain.
You might have heard, or will hear about, libraries dedicated to machine learning such as [scikit-learn](https://en.wikipedia.org/wiki/Scikit-learn) or Google's [TensorFlow](https://en.wikipedia.org/wiki/TensorFlow) to build neural networks.

The most widely used library in Python to store arrays of numbers and perform computations on them work is [NumPy](https://en.wikipedia.org/wiki/NumPy).
NumPy is a library for scientific computing, providing optimized data structures and operations, mathematical functions, linear algebra routines, etc

NumPy's optimized implementation in [the C programming language](https://en.wikipedia.org/wiki/C_(programming_language) enables you to benefit from this, which means your operations on numbers can run faster than in pure Python.


To use NumPy in your notebook or program, you need to import it as follows

In [ ]:
import numpy as np

Here we imported the NumPy library, and gave it a shorter name `np` that we can use whenever we need to use one of its functionalities.

### Array creation

NumPy arrays can be created from Python lists

In [ ]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

NumPy supports arrays of arbitrary dimension.

For example, we can create two-dimensional arrays (e.g. to store a matrix) as follows

In [ ]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
my_2d_array

array([[1, 2, 3],
       [4, 5, 6]])

We can access individual elements of a 2d-array using two indices

In [ ]:
my_2d_array[1, 2]

6

We can also access rows

In [ ]:
my_2d_array[1]

array([4, 5, 6])

and columns

In [ ]:
my_2d_array[:, 2]

array([3, 6])

NumPy arrays have a `shape` attribute.

An *attribute* is a variable that is attached to an object, the same way a method is attached to an object (cf. `list.append` earlier).

In [ ]:
print(my_array.shape)
print(my_2d_array.shape)

(3,)
(2, 3)


Contrary to Python lists, NumPy arrays must have a type and all elements of the array must have the same type.
Here, `dtype` is another attribute of the array.

In [ ]:
my_array.dtype

dtype('int64')

The main types are `int32` (32-bit integers), `int64` (64-bit integers), `float32` (32-bit real values) and `float64` (64-bit real values).

The `dtype` can be specified when creating the array

In [ ]:
my_array = np.array([1, 2, 3], dtype=np.float64)
my_array.dtype

dtype('float64')

We can create arrays of all zeros using the numpy function `zeros`.

Here we create a matrix, a 2-D array, with 2 rows and 3 columns.

In [ ]:
zero_array = np.zeros((2, 3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

Similarly, the function `ones` creates an array with 1 in each cell.

**Exercise.** Create an array of 5 rows and 4 columns, filled with ones.

Similar to the `range` function in the Python standard library, in numpy we can create a range of values using the [arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) function.

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

If a unique argument is provided, the starting value is assumed to be 0, but you can specify the starting (included) and ending (excluded) values

In [ ]:
np.arange(3, 5)

array([3, 4])

Another useful routine is `linspace` for creating linearly spaced values in an interval. For instance, to create 10 values in `[0, 1]`, we can use

In [ ]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Another important operation on NumPy arrays is [reshape](https://numpy.org/doc/stable/user/quickstart.html?highlight=reshape#changing-the-shape-of-an-array), for changing the shape of an array

In [ ]:
# 1d array
my_array = np.array([1, 2, 3, 4, 5, 6])
my_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
# reshape into a 3 rows, 2 cols array
# we call the reshape() method on the my_array object
my_array.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

You can play with these operations and make sure you understand them well.

### Basic operations

In NumPy, we express computations directly over arrays. This makes the code much more succint.

Arithmetic operations can be performed directly over arrays. For instance, assuming two arrays have a compatible shape, we can add them as follows

In [ ]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
array_a + array_b

array([5, 7, 9])

Compare this with the equivalent computation using a for loop

In [ ]:
# create an array with the same shape as array_a, but filled with 0s
array_out = np.zeros_like(array_a)
# sum element-wise
for i in range(len(array_a)):
  array_out[i] = array_a[i] + array_b[i]
array_out

array([5, 7, 9])

Not only this code is more verbose, it will also run much more slowly.

In NumPy, functions that operate on arrays in an element-wise fashion are called [universal functions](https://numpy.org/doc/stable/reference/ufuncs.html). For instance, this is the case of `np.sin`

In [ ]:
np.sin(array_a)

array([0.84147098, 0.90929743, 0.14112001])

[Vector inner product](https://en.wikipedia.org/wiki/Dot_product) can be performed using `np.dot`

In [ ]:
np.dot(array_a, array_b)

32

#### Advanced notions (optional)
When the two arguments to `np.dot` are both 2d arrays, `np.dot` becomes matrix multiplication

In [ ]:
# A: random values from a uniform distribution over [0, 1)
array_A = np.random.rand(5, 3)
array_A

array([[0.67820903, 0.43824677, 0.1168565 ],
       [0.87493485, 0.74637326, 0.66845354],
       [0.84174041, 0.56758632, 0.69959319],
       [0.48425096, 0.12418178, 0.82069518],
       [0.35857016, 0.42358637, 0.76601952]])

In [ ]:
# B: random values from the standard normal distribution
array_B = np.random.randn(3, 4)
array_B

array([[-0.0939625 , -0.10379045,  0.00377791,  0.89752424],
       [-1.70291436,  1.22072069, -1.41558762,  1.73743372],
       [-0.43694199, -1.88874156, -1.2437126 , -0.59502533]])

In [ ]:
np.dot(array_A, array_B)

array([[-0.86108245,  0.24387354, -0.76315039,  1.30060118],
       [-1.64529622, -0.44223258, -1.88461541,  1.68430251],
       [-1.35132458, -0.71585099, -1.67038103,  1.32535037],
       [-0.61556856, -1.44875046, -1.19466969,  0.16205017],
       [-1.08972956, -0.96694841, -1.55097711,  0.60197765]])

Matrix transpose can be done using `.transpose()` or `.T` for short

In [ ]:
array_A.T

array([[0.84254571, 0.8729602 , 0.76196144, 0.87053858, 0.55601909],
       [0.40069714, 0.48700109, 0.53893757, 0.76891072, 0.40953449],
       [0.36015303, 0.53530548, 0.19596679, 0.59329035, 0.52866948]])

### Slicing and masking

Like Python lists, NumPy arrays support slicing.

In [ ]:
np.arange(10)[5:]

array([5, 6, 7, 8, 9])

We can also select only certain elements from the array, by filtering on a boolean mask that applies if a condition is True.

In [ ]:
# create values from 0 to 10 (= up to 9 included)
x = np.arange(10)
# mask all values in x that are greather than 5
mask = x >= 5
# print the mask : False for values 0 to 4 included, True for 5 and up
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
# apply the mask to x itself
x[mask]

array([5, 6, 7, 8, 9])

### Exercices

**Exercise 1.** Create a 3d array of shape (2, 2, 2), containing 8 values. Access individual elements and slices.

In [ ]:
a = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a.shape

(2, 2, 2)

Retrieve values `1` and `5`.

array([1, 5])

**Exercise 2.** Rewrite the relu function (see Python section) using [np.maximum](https://numpy.org/doc/stable/reference/generated/numpy.maximum.html). Check that it works on both a single value and on an array of values.

> **HINT** `0` is greater than any negative integer, but smaller than any positive integer.



In [ ]:
def relu_numpy(x):
  # write your function here
  return

In [ ]:
# should output 0
relu_numpy(-3)

In [ ]:
# should output 2
relu_numpy(2)

In [ ]:
# should output [1, 0, 2.5]
relu_numpy(np.array([1, -3, 2.5]))

**Exercise 3.** Rewrite the average of a vector (1d array) using NumPy (without for loop), with [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html) and the shape of the array.

In [ ]:
def average_numpy(vector):
  # write your function here
  return

In [ ]:
my_vector = np.array([12, 11, 9, 5, 7])
# the result should be 8.8
average(my_vector)

Compare with what you get with [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

### Going further

* [Scientific Computing in Python: Introduction to NumPy and Matplotlib](https://sebastianraschka.com/blog/2020/numpy-intro.html)
* [NumPy reference](https://numpy.org/doc/stable/reference/)
* [SciPy lectures](https://scipy-lectures.org/)
* One-hour [tutorial](https://www.youtube.com/watch?v=QUT1VHiLmmI) on Youtube